version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  lint_dockerfiles:
     docker:
       - image: circleci/python:3.9-buster-node-browsers-legacy
     steps:
      - checkout
      - run: 
         name: "Install hadolint from source"
         command: |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint
      - run: 
         name: "Lint Dockerfiles"
         command: |
            /bin/hadolint ./Dockerfile
            /bin/hadolint ./db/Dockerfile
      - run:
         name: "On failure"
         command: |
            echo "Linting Dockerfiles has failed"
         when: on_fail
            

workflows:
  main-workflow:
    jobs:
      - lint_dockerfiles
      - aws-ecr/build-and-push-image:
          path: .
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          registry-id: AWS_ECR_REGISTRY_ID
          region: ${AWS_DEFAULT_REGION}
          repo: ecomm-lamp-app
          tag: "latest,${CIRCLE_SHA1:0:7}"
      - aws-ecr/build-and-push-image:
          path: ./db
          workspace-root: ./db
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          registry-id: AWS_ECR_REGISTRY_ID
          region: ${AWS_DEFAULT_REGION}
          repo: mariadb
          tag: "latest,${CIRCLE_SHA1:0:7}"