version: 2.1

# TODO: Create smoke and rollback steps
# TODO: Allow toggle between green and blue (create toggle file in S3 to maintain state)

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

commands:
  install_terraform:
    parameters:
      AWS_ACCESS_KEY_ID:
        default: "${AWS_ACCESS_KEY_ID}"
        type: string
      AWS_SECRET_ACCESS_KEY:
        default: "${AWS_SECRET_ACCESS_KEY}"
        type: string
    steps:
      - run:
         name: "Install Terraform Open Source"
         command: |
            sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
            sudo apt-get install -y lsb-release && sudo apt-get clean all
            wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
            gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt update && sudo apt install -y terraform

            terraform -help

            if [ "$?" != "0" ];then
              exit 1
            fi
      - run:
         name: "Failed to install Terraform"
         command: |
             echo "Terraform failed to install....."
         when: on_fail
 
  smoke_test:
    steps:
     - run:
        name: "curl endpoint and check if valid HTTP 200 is returned"
        command: |
         ## TODO
         curl "" 

  rollback_deployment:
    steps:
      - run:
         name: "Rollback Terraform to the original state"
         working_directory: ~/project/tf
         command: |
           terraform apply -var-file=variables/development.tfvars -var is_green="false" -auto-approve
      - run:
         name: "Failed to rollback"
         command: |
           echo "Failed to rollback, manual intervention required"
         when: on_fail

jobs:
  lint_dockerfiles:
     docker:
      - image: circleci/python:3.9
     steps:
      - checkout
      - run: 
         name: "Install hadolint from source"
         command: |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint
      - run: 
         name: "Lint Dockerfiles"
         command: |
            /bin/hadolint ./Dockerfile
            /bin/hadolint ./db/Dockerfile
      - run:
         name: "On failure"
         command: |
            echo "Linting Dockerfiles has failed"
         when: on_fail

  deploy_new_env:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - install_terraform
      - run:
         name: "Initialize Terraform"
         working_directory: ~/project/tf
         command: |
           terraform init
      - run:
         name: "Deploy Green ECS Service"
         working_directory: ~/project/tf
         command: |
           terraform apply -var-file=variables/development.tfvars -var is_green="true" -auto-approve
      - run:
         name: "Failed to Deploy Green Environment"
         command: |
           echo "Failed to deploy Green Environment"
         when: on_fail

  apply_traffic_90_10:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - install_terraform
      - run:
         name: "Initialize Terraform"
         working_directory: ~/project/tf
         command: |
           terraform init
      - run:
         name: "Move 10% of Traffic to Green"
         working_directory: ~/project/tf
         command: |
           terraform apply -var-file=variables/development.tfvars -var is_green="true" -var traffic_distribution="blue-90" -auto-approve
      - run:
         name: "Failed to redistribute traffic 90/10"
         command: |
            echo "Failed to redistribute traffic 90/10, rolling back to previous state"
         when: on_fail

  apply_traffic_0_100:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - install_terraform
      - run:
         name: "Initialize Terraform"
         working_directory: ~/project/tf
         command: |
            terraform init
      - run:
         name: "Move 10% of Traffic to Green"
         working_directory: ~/project/tf
         command: |
            terraform apply -var-file=variables/development.tfvars -var is_green="true" -var traffic_distribution="green" -auto-approve
      - run:
         name: "Failed to redistribute traffic"
         command: |
            echo "Failed to redistribute traffic, rolling back to previous state"
         when: on_fail

  destroy_old_env:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - install_terraform
      - run:
         name: "Initialize Terraform"
         working_directory: ~/project/tf
         command: |
            terraform init
      - run:
         name: "Destroy old environment"
         working_directory: ~/project/tf
         command: |
            terraform apply -var-file=variables/development.tfvars -var is_green="true" -var is_blue="false" -var traffic_distribution="green" -auto-approve
      - run:
         name: "Failed to redistribute traffic"
         command: |
            echo "Failed to redistribute traffic, rolling back to previous state"
         when: on_fail


workflows:
  main-workflow:
    jobs:
      - lint_dockerfiles
      - aws-ecr/build-and-push-image:
          path: .
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          registry-id: AWS_ECR_REGISTRY_ID
          region: ${AWS_DEFAULT_REGION}
          repo: ecomm-lamp-app
          tag: "latest,${CIRCLE_SHA1:0:7}"
      - aws-ecr/build-and-push-image:
          path: ./db
          workspace-root: ./db
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          registry-id: AWS_ECR_REGISTRY_ID
          region: ${AWS_DEFAULT_REGION}
          repo: mariadb
          tag: "latest,${CIRCLE_SHA1:0:7}"
      - deploy_new_env
      - apply_traffic_90_10
      - apply_traffic_0_100
      - destroy_old_env